import type { Metadata } from "next"
import { Anek_Devanagari } from "next/font/google"
import "./globals.css"
import { Toaster } from "sonner"
import Link from "next/link"
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/mode-toggle"
import Navbar from "@/components/navbar"
import { createSupabaseAppServerClient } from "./supabase/server"
const anek = Anek_Devanagari({
	weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {

	const supabase = createSupabaseAppServerClient()
	const {user} =  (await supabase.auth.getUser()).data
	return (
		<html lang="fr">
			<Toaster />
			<body className={`${anek.className} h-screen  overflow-hidden w-screen bg-background`}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					<Navbar user={user} />
					{children}
				</ThemeProvider>
			</body>
		</html>
	)
}
